# Generated by Django 4.2.4 on 2025-08-21 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('brand', models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Tecno', 'Tecno'), ('Infinix', 'Infinix'), ('Xiaomi/POCO', 'Xiaomi/POCO'), ('OPPO', 'OPPO'), ('Others', 'Others')], max_length=32)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('price_min_ksh', models.PositiveIntegerField()),
                ('price_max_ksh', models.PositiveIntegerField(blank=True, null=True)),
                ('ram_gb', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('storage_gb', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('battery_mah', models.PositiveIntegerField(blank=True, null=True)),
                ('camera_mp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('display_inches', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('display_type', models.CharField(blank=True, max_length=40)),
                ('specs_text', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='smartphones/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smartphone', to='products.product')),
            ],
            options={
                'ordering': ['brand', 'name'],
                'indexes': [models.Index(fields=['brand'], name='smartphones_brand_fbf8fa_idx'), models.Index(fields=['slug'], name='smartphones_slug_4a9bc9_idx')],
            },
        ),
    ]
