# Generated by Django 4.2.4 on 2025-08-21 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Television',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('brand', models.CharField(choices=[('Samsung', 'Samsung'), ('LG', 'LG'), ('Sony', 'Sony'), ('Hisense', 'Hisense'), ('Vitron', 'Vitron'), ('TCL', 'TCL'), ('Unbranded', 'Unbranded')], max_length=24)),
                ('screen_size_inches', models.PositiveSmallIntegerField(help_text='Diagonal size in inches, e.g. 55')),
                ('panel', models.CharField(choices=[('LED', 'LED'), ('QLED', 'QLED'), ('OLED', 'OLED'), ('NanoCell', 'NanoCell'), ('Crystal', 'Crystal'), ('Other', 'Other')], default='LED', max_length=16)),
                ('resolution', models.CharField(choices=[('HD', 'HD (720p)'), ('FHD', 'Full HD (1080p)'), ('UHD', '4K UHD'), ('8K', '8K')], default='UHD', max_length=8)),
                ('smart', models.BooleanField(default=True)),
                ('hdr', models.BooleanField(default=True)),
                ('refresh_rate_hz', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('price_min_ksh', models.PositiveIntegerField()),
                ('price_max_ksh', models.PositiveIntegerField(blank=True, null=True)),
                ('specs_text', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='televisions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='television', to='products.product')),
            ],
            options={
                'ordering': ['brand', 'screen_size_inches', 'name'],
                'indexes': [models.Index(fields=['brand'], name='televisions_brand_6cb9bd_idx'), models.Index(fields=['slug'], name='televisions_slug_6618d5_idx'), models.Index(fields=['resolution'], name='televisions_resolut_b351a6_idx'), models.Index(fields=['panel'], name='televisions_panel_df1725_idx')],
            },
        ),
    ]
