# Generated by Django 4.2.4 on 2025-08-22 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSmartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('brand', models.CharField(choices=[('Xiaomi', 'Xiaomi'), ('Infinix', 'Infinix'), ('Samsung', 'Samsung'), ('Tecno', 'Tecno'), ('Itel', 'Itel'), ('Realme', 'Realme'), ('Nokia', 'Nokia'), ('Vivo', 'Vivo'), ('Oppo', 'Oppo'), ('Villaon', 'Villaon'), ('Unbranded', 'Unbranded')], max_length=32)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('price_min_ksh', models.PositiveIntegerField()),
                ('price_max_ksh', models.PositiveIntegerField(blank=True, null=True)),
                ('badge', models.CharField(blank=True, default='', max_length=24)),
                ('specs_text', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.ImageField(upload_to='budgetsmartphones/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_smartphone', to='products.product')),
            ],
            options={
                'ordering': ['brand', 'name'],
                'indexes': [models.Index(fields=['brand'], name='budgetsmart_brand_b2921f_idx'), models.Index(fields=['slug'], name='budgetsmart_slug_68492a_idx')],
            },
        ),
    ]
