# Generated by Django 4.2.4 on 2025-08-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('brand', models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Lenovo', 'Lenovo'), ('Huawei', 'Huawei'), ('TabletsForKids', 'Tablets for Kids')], max_length=32)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('price_min_ksh', models.PositiveIntegerField()),
                ('price_max_ksh', models.PositiveIntegerField(blank=True, null=True)),
                ('ram_gb', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('storage_gb', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('display_inches', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('display_type', models.CharField(blank=True, max_length=40)),
                ('specs_text', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='tablets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['brand', 'name'],
                'indexes': [models.Index(fields=['brand'], name='tablets_tab_brand_018526_idx'), models.Index(fields=['slug'], name='tablets_tab_slug_c2918b_idx')],
            },
        ),
    ]
