# Generated by Django 4.2.4 on 2025-08-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablet',
            name='brand',
            field=models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Lenovo', 'Lenovo'), ('Huawei', 'Huawei'), ('TabletsForKids', 'Tablets for Kids'), ('Others', 'Others')], max_length=32),
        ),
    ]
