# Generated by Django 4.2.4 on 2025-08-21 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart_cartitem'),
        ('tablets', '0003_alter_tablet_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablet',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tablet', to='products.product'),
        ),
    ]
