# Generated by Django 4.2.4 on 2025-08-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_pdf',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
