# Generated by Django 4.2.4 on 2025-08-22 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewIphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('new_price_ksh', models.PositiveIntegerField()),
                ('old_price_ksh', models.PositiveIntegerField(blank=True, null=True)),
                ('badge', models.CharField(choices=[('HOT', 'Hot'), ('NEW', 'New'), ('SALE', 'Sale'), ('NONE', 'None')], default='NONE', max_length=8)),
                ('specs_text', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='new_iphones/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='new_iphones/banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_iphone', to='products.product')),
            ],
            options={
                'ordering': ['-created_at', 'name'],
                'indexes': [models.Index(fields=['slug'], name='newiphones__slug_23fd0e_idx'), models.Index(fields=['created_at'], name='newiphones__created_1adc98_idx')],
            },
        ),
    ]
