# Generated by Django 4.2.4 on 2025-08-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newiphones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewIphoneBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='new_iphones/global_banner/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'New iPhones Banner',
                'verbose_name_plural': 'New iPhones Banner',
            },
        ),
    ]
