# Generated by Django 4.2.4 on 2025-08-21 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('brand', models.CharField(choices=[('JBL', 'JBL'), ('Sony', 'Sony'), ('Samsung', 'Samsung'), ('Anker', 'Anker'), ('Harman Kardon', 'Harman Kardon'), ('Bose', 'Bose'), ('Unbranded', 'Unbranded')], max_length=32)),
                ('category', models.CharField(choices=[('Buds', 'Buds'), ('Earphones', 'Earphones'), ('Speakers', 'Speakers'), ('Headphones', 'Headphones'), ('Soundbars', 'Soundbars'), ('Microphones', 'Microphones'), ('Others', 'Others')], max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('price_min_ksh', models.PositiveIntegerField()),
                ('price_max_ksh', models.PositiveIntegerField(blank=True, null=True)),
                ('specs_text', models.CharField(blank=True, max_length=255)),
                ('wireless', models.BooleanField(default=True)),
                ('anc', models.BooleanField(default=False, verbose_name='Active Noise Cancelling')),
                ('battery_life_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_device', to='products.product')),
            ],
            options={
                'ordering': ['brand', 'name'],
                'indexes': [models.Index(fields=['brand'], name='audio_audio_brand_405ebc_idx'), models.Index(fields=['category'], name='audio_audio_categor_95c162_idx'), models.Index(fields=['slug'], name='audio_audio_slug_de2d09_idx')],
            },
        ),
    ]
