# Generated by Django 4.2.4 on 2025-08-21 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MkopaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('brand', models.CharField(choices=[('Samsung', 'Samsung'), ('M-KOPA', 'M-KOPA'), ('Nokia', 'Nokia'), ('Tecno', 'Tecno'), ('Infinix', 'Infinix'), ('itel', 'itel'), ('Unbranded', 'Unbranded')], max_length=32)),
                ('category', models.CharField(choices=[('Smartphones', 'Smartphones'), ('Feature Phones', 'Feature Phones'), ('Others', 'Others')], max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('price_min_ksh', models.PositiveIntegerField()),
                ('price_max_ksh', models.PositiveIntegerField(blank=True, null=True)),
                ('deposit_ksh', models.PositiveIntegerField(default=0)),
                ('weekly_ksh', models.PositiveIntegerField(default=0)),
                ('term_weeks', models.PositiveSmallIntegerField(default=0)),
                ('specs_text', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='mkopa/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mkopa_item', to='products.product')),
            ],
            options={
                'ordering': ['brand', 'name'],
                'indexes': [models.Index(fields=['brand'], name='mkopa_mkopa_brand_aad088_idx'), models.Index(fields=['category'], name='mkopa_mkopa_categor_705ce2_idx'), models.Index(fields=['slug'], name='mkopa_mkopa_slug_eafe47_idx')],
            },
        ),
    ]
