# Generated by Django 4.2.4 on 2025-08-21 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('brand', models.CharField(choices=[('Samsung', 'Samsung'), ('Xiaomi', 'Xiaomi'), ('realme', 'realme'), ('Tecno', 'Tecno'), ('Infinix', 'Infinix'), ('Apple', 'Apple'), ('Vivo', 'Vivo'), ('Other', 'Other')], default='Other', max_length=24)),
                ('category', models.CharField(choices=[('Smartphone', 'Smartphone'), ('Accessory', 'Accessory'), ('Tablet', 'Tablet'), ('Television', 'Television'), ('Laptop', 'Laptop'), ('Other', 'Other')], default='Other', max_length=24)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('price_min_ksh', models.PositiveIntegerField()),
                ('price_max_ksh', models.PositiveIntegerField(blank=True, null=True)),
                ('old_price_ksh', models.PositiveIntegerField(blank=True, null=True)),
                ('labels_csv', models.CharField(blank=True, help_text='Comma-separated labels, e.g. NEW,HOT,SALE', max_length=160)),
                ('image', models.ImageField(upload_to='offers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_offer', to='products.product')),
            ],
            options={
                'ordering': ['-created_at', 'name'],
                'indexes': [models.Index(fields=['brand'], name='offers_late_brand_716c2c_idx'), models.Index(fields=['category'], name='offers_late_categor_0f47b8_idx'), models.Index(fields=['slug'], name='offers_late_slug_9a1063_idx'), models.Index(fields=['-created_at'], name='offers_late_created_be10fd_idx')],
            },
        ),
    ]
