# Generated by Django 4.2.4 on 2025-08-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('brand', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Anker', 'Anker'), ('UGreen', 'UGreen'), ('Baseus', 'Baseus'), ('Oraimo', 'Oraimo'), ('Xiaomi', 'Xiaomi'), ('Huawei', 'Huawei'), ('OnePlus', 'OnePlus'), ('Amaya', 'Amaya'), ('Unbranded', 'Unbranded')], max_length=32)),
                ('category', models.CharField(choices=[('Chargers', 'Chargers'), ('Powerbanks', 'Powerbanks'), ('Phone Covers', 'Phone Covers'), ('Protectors', 'Protectors'), ('Cables', 'Cables'), ('Mounts', 'Mounts'), ('Earbuds Cases', 'Earbuds Cases'), ('Others', 'Others')], max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('price_min_ksh', models.PositiveIntegerField()),
                ('price_max_ksh', models.PositiveIntegerField(blank=True, null=True)),
                ('specs_text', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='accessories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory', to='products.product')),
            ],
            options={
                'ordering': ['brand', 'name'],
                'indexes': [models.Index(fields=['brand'], name='accessories_brand_f138c2_idx'), models.Index(fields=['category'], name='accessories_categor_d754da_idx'), models.Index(fields=['slug'], name='accessories_slug_2bc921_idx')],
            },
        ),
    ]
