# Generated by Django 4.2.4 on 2025-08-21 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('brand', models.CharField(choices=[('SanDisk', 'SanDisk'), ('WD', 'Western Digital (WD)'), ('Seagate', 'Seagate'), ('Toshiba', 'Toshiba'), ('Samsung', 'Samsung'), ('Crucial', 'Crucial'), ('Transcend', 'Transcend'), ('LaCie', 'LaCie'), ('Verbatim', 'Verbatim'), ('PNY', 'PNY'), ('Others', 'Others')], max_length=32)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('price_min_ksh', models.PositiveIntegerField()),
                ('price_max_ksh', models.PositiveIntegerField(blank=True, null=True)),
                ('capacity_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('interface', models.CharField(blank=True, max_length=40)),
                ('form_factor', models.CharField(blank=True, max_length=40)),
                ('specs_text', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='storages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_device', to='products.product')),
            ],
            options={
                'ordering': ['brand', 'name'],
                'indexes': [models.Index(fields=['brand'], name='storages_st_brand_a00b9c_idx'), models.Index(fields=['slug'], name='storages_st_slug_e467ab_idx')],
            },
        ),
    ]
